version: '3.8'

services:
  api:
    image: andt123/energy-efficient-app:backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./energy-efficiency-app
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://api:5000/api
